<a href="https://colab.research.google.com/github/Skshamim02/Machine_transliteration/blob/main/MachineTransliterationFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install fasttext

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.8/68.8 kB 5.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
  Created wheel for fasttext: filename=fasttext-0.9.2-cp310-cp310-linux_x86_64.whl size=4393266 sha256=2c275bbeac97976b20a7f36bbdc4e85285772f8438cd8115d1da1ee899b9cfff
  Stored in directory: /root/.cache/pip/wheels/a5/13/75/f811c84a8ab36eedbaef977a6a58a98990e8e0f1967f98f394
Successfully built fasttext


In [ ]:
import fasttext

The following code loads a pretrained English FastText model from the specified file path using the fasttext library and assigns it to the variable english_model.

In [ ]:
# Path to the pretrained English FastText model
english_model_path = '/content/drive/MyDrive/Colab Notebooks/cc.en.300.bin'

# Load the pretrained English FastText model
english_model = fasttext.load_model(english_model_path)

In [ ]:
english_model.get_dimension()

300

In [ ]:
import pandas as pd
import json

In [ ]:
# Read the CSV file using pandas
train_data_frame = pd.read_json('/content/drive/MyDrive/Colab Notebooks/mni_train.json',lines=True)
train_data_frame

unique_identifier  native word      english word     source     score
0                  mni1         ꯂꯨꯗꯨ              ludu    AK-Freq       NaN
1                  mni2        ꯑꯣꯛꯁꯥ             oksha    AK-Freq       NaN
2                  mni3        ꯊꯝꯕꯥꯜ           thambal    AK-Freq       NaN
3                  mni4  ꯂꯦꯡꯊꯩꯅꯕꯁꯤꯗꯤ  lengtheinabasidi    AK-Freq       NaN
4                  mni5     ꯑꯦꯄ꯭ꯂꯥꯢꯗ           applied    AK-Freq       NaN
...                 ...          ...               ...        ...       ...
10055          mni10056        ꯄꯥꯡꯒꯂ          panggala  IndicCorp -0.174713
10056          mni10057    ꯈꯣꯔꯤꯔꯣꯂꯒꯤ       khorirolagi  IndicCorp -0.160257
10057          mni10058       ꯃꯁꯤꯡꯈꯥ        masingkhaa  IndicCorp -0.089934
10058          mni10059        ꯄꯣꯛꯄꯥ            pokpaa  IndicCorp -0.174966
10059          mni10060     ꯁꯅꯥꯖꯥꯎꯕꯅ       sanajaobana  IndicCorp -0.303592

[10060 rows x 5 columns]

 the following code separates the 'native word' and 'english word' columns from the train_data_frame DataFrame and assigns them to mni_words and eng_words, respectively

In [ ]:

features = train_data_frame.copy()
mni_words = features.pop('native word')
eng_words = features.pop('english word')
eng_words

0                    ludu
1                   oksha
2                 thambal
3        lengtheinabasidi
4                 applied
               ...       
10055            panggala
10056         khorirolagi
10057          masingkhaa
10058              pokpaa
10059         sanajaobana
Name: english word, Length: 10060, dtype: object

In [ ]:
# Prepare the training data file
#with open('/content/drive/MyDrive/Colab Notebooks/train_mni_Mtei.txt', 'a', encoding='utf-8') as f:
 #   for text in mni_words:
  #      f.write(text + '\n')

In [ ]:
manipuri_model = fasttext.train_unsupervised('/content/drive/MyDrive/Colab Notebooks/train_mni_Mtei.txt', minn=1, maxn=5, dim=100)

In [ ]:
manipuri_model.save_model("/content/drive/MyDrive/Colab Notebooks/mm_word_min2_emb_trained.bin")

In [ ]:
manipuri_model.get_word_vector("ꯃ")

array([ 0.6619944 , -0.16315717, -0.30044603, -0.28545722, -0.5235201 ,
       -0.15174791, -0.66545326,  0.15887249, -0.6327333 ,  0.13369572,
       -0.6466927 ,  0.79841024, -0.40792543,  0.36684307, -0.78038985,
       -0.36784878,  0.6376195 ,  1.0512756 , -0.90076894, -0.26770306,
       -0.29650125,  0.581595  , -0.47365162,  0.21367358, -0.18608096,
        0.0167257 ,  0.2632734 , -0.7259229 , -1.011928  , -0.05054175,
        0.36914006, -0.66099715,  0.16792597, -0.35279256, -1.0820861 ,
       -0.15252692, -0.58705634,  0.13675709, -0.5529628 , -0.25291088,
       -0.00582439,  0.8513531 ,  0.08126765,  0.6232831 , -0.66333723,
        0.30611265, -0.9358799 ,  0.74637824,  0.920117  , -0.6661053 ,
       -0.29782978, -0.5366821 , -0.31153995,  0.11762436, -0.5079255 ,
        0.20218125, -0.13303576, -0.97142977, -0.1973783 ,  0.15495472,
        0.38155687,  0.211322  ,  1.3614364 ,  0.23373489,  0.472325  ,
       -0.4221649 , -0.12420378, -0.05897048, -0.9241838 ,  0.23

In [ ]:
manipuri_model.get_dimension()

100

In [ ]:
# Function to split a word into characters
def split_word_into_characters(word):
    return ' '.join(list(word))

# Apply character splitting to English dataframe
eng_words = eng_words.apply(split_word_into_characters)

# Apply character splitting to Manipuri dataframe
mni_words = mni_words.apply(split_word_into_characters)

# Print the updated dataframes
print(eng_words)
print(mni_words)

0                                l u d u
1                              o k s h a
2                          t h a m b a l
3        l e n g t h e i n a b a s i d i
4                          a p p l i e d
                      ...               
10055                    p a n g g a l a
10056              k h o r i r o l a g i
10057                m a s i n g k h a a
10058                        p o k p a a
10059              s a n a j a o b a n a
Name: english word, Length: 10060, dtype: object
0                      ꯂ ꯨ ꯗ ꯨ
1                    ꯑ ꯣ ꯛ ꯁ ꯥ
2                    ꯊ ꯝ ꯕ ꯥ ꯜ
3        ꯂ ꯦ ꯡ ꯊ ꯩ ꯅ ꯕ ꯁ ꯤ ꯗ ꯤ
4              ꯑ ꯦ ꯄ ꯭ ꯂ ꯥ ꯢ ꯗ
                 ...          
10055                ꯄ ꯥ ꯡ ꯒ ꯂ
10056        ꯈ ꯣ ꯔ ꯤ ꯔ ꯣ ꯂ ꯒ ꯤ
10057              ꯃ ꯁ ꯤ ꯡ ꯈ ꯥ
10058                ꯄ ꯣ ꯛ ꯄ ꯥ
10059          ꯁ ꯅ ꯥ ꯖ ꯥ ꯎ ꯕ ꯅ
Name: native word, Length: 10060, dtype: object


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

### Tokenization

In [ ]:
# Preprocess the input by removing spaces
eng_words_preprocessed = [word.replace(' ', '') for word in eng_words]
mni_words_preprocessed = [word.replace(' ', '') for word in mni_words]

In [ ]:
# Initialize a tokenizer for English words with character-level tokenization
eng_tokenizer = Tokenizer(char_level=True)
eng_tokenizer.fit_on_texts(eng_words_preprocessed)

# Convert the English words into sequences of integers using the fitted tokenizer
eng_sequences = eng_tokenizer.texts_to_sequences(eng_words_preprocessed)

mni_tokenizer = Tokenizer(char_level=True)
mni_tokenizer.fit_on_texts(mni_words_preprocessed)
mni_sequences = mni_tokenizer.texts_to_sequences(mni_words_preprocessed)

In [ ]:
len(mni_tokenizer.word_index)

44

### Padding

In [ ]:
#calculates the maximum sequence length among all the sequences in both eng_sequences and mni_sequences.
max_seq_length = max(max(len(seq) for seq in eng_sequences), max(len(seq) for seq in mni_sequences))
eng_sequences_padded = pad_sequences(eng_sequences, maxlen=max_seq_length, padding='post')
mni_sequences_padded = pad_sequences(mni_sequences, maxlen=max_seq_length, padding='post')
max_seq_length

22

In [ ]:
# Print the padded sequences
print(eng_sequences_padded)
print(mni_sequences_padded)

[[12 10 17 ...  0  0  0]
 [ 9  6 13 ...  0  0  0]
 [ 8  4  1 ...  0  0  0]
 ...
 [ 7  1 13 ...  0  0  0]
 [14  9  6 ...  0  0  0]
 [13  1  3 ...  0  0  0]]
[[ 9  6 11 ...  0  0  0]
 [27  8 19 ...  0  0  0]
 [23 17  5 ...  0  0  0]
 ...
 [13  4  1 ...  0  0  0]
 [14  8 19 ...  0  0  0]
 [ 4  3  2 ...  0  0  0]]


In [ ]:
mni_sequences_padded[0]

array([ 9,  6, 11,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0], dtype=int32)

### Create word embeddings using FastText model

In [ ]:
import numpy as np
eng_word_embeddings = np.zeros((len(eng_tokenizer.word_index) + 1, english_model.get_dimension()))
mni_word_embeddings = np.zeros((len(mni_tokenizer.word_index) + 1, manipuri_model.get_dimension()))

In [ ]:
for word, index in eng_tokenizer.word_index.items():
    if word in english_model:
        eng_word_embeddings[index] = english_model[word]

for word, index in mni_tokenizer.word_index.items():
    if word in manipuri_model:
        mni_word_embeddings[index] = manipuri_model[word]

In [ ]:
mni_tokenizer.word_index.items()

dict_items([('ꯤ', 1), ('ꯥ', 2), ('ꯅ', 3), ('ꯁ', 4), ('ꯕ', 5), ('ꯨ', 6), ('ꯔ', 7), ('ꯣ', 8), ('ꯂ', 9), ('ꯡ', 10), ('ꯗ', 11), ('ꯟ', 12), ('ꯃ', 13), ('ꯄ', 14), ('ꯒ', 15), ('ꯦ', 16), ('ꯝ', 17), ('ꯇ', 18), ('ꯛ', 19), ('ꯀ', 20), ('ꯈ', 21), ('ꯌ', 22), ('ꯊ', 23), ('ꯍ', 24), ('ꯆ', 25), ('ꯩ', 26), ('ꯑ', 27), ('ꯐ', 28), ('ꯠ', 29), ('ꯜ', 30), ('ꯢ', 31), ('ꯧ', 32), ('ꯏ', 33), ('ꯖ', 34), ('ꯋ', 35), ('꯭', 36), ('ꯉ', 37), ('ꯎ', 38), ('ꯪ', 39), ('ꯞ', 40), ('ꯚ', 41), ('ꯓ', 42), ('ꯙ', 43), ('ꯘ', 44)])

### Define Encoder-Decoder Model

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Embedding, RepeatVector

#encoder_input is defined as an input layer with a shape of (max_seq_length,), representing the input sequences.
encoder_input = Input(shape=(max_seq_length,))
#encoder_embedding is the embedding layer that takes the encoder_input as input.
encoder_embedding = Embedding(len(eng_tokenizer.word_index) + 1, english_model.get_dimension(), weights=[eng_word_embeddings], trainable=False)(encoder_input)
#encoder is an LSTM layer with 256 units that takes the embedded input sequences (encoder_embedding) as input and processes them to produce an encoded representation.
encoder = LSTM(256)(encoder_embedding)

#RepeatVector layer repeats the encoded representation max_seq_length times to align with the target sequence length.
decoder = RepeatVector(max_seq_length)(encoder)
#Another LSTM layer with 256 units is used as the decoder, taking the repeated encoded representation (decoder) as input and generating a sequence of outputs.
#the RepeatVector layer serves as a way to provide the context vector to each time step of the decoder, as it repeats the context vector to align with the target sequence length.
#The actual passing of hidden states between time steps is handled internally by the LSTM layer.
decoder = LSTM(256, return_sequences=True)(decoder)
#decoder_output is a Dense layer with the number of units equal to the size of the Mni vocabulary
decoder_output = Dense(len(mni_tokenizer.word_index) + 1, activation='softmax')(decoder)

In [ ]:
model = Model(inputs=encoder_input, outputs=decoder_output)

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 22)]              0         
                                                                 
 embedding (Embedding)       (None, 22, 300)           8100      
                                                                 
 lstm (LSTM)                 (None, 256)               570368    
                                                                 
 repeat_vector (RepeatVector  (None, 22, 256)          0         
 )                                                               
                                                                 
 lstm_1 (LSTM)               (None, 22, 256)           525312    
                                                                 
 dense (Dense)               (None, 22, 45)            11565     
                                                             

In [ ]:
# Model Training
model.fit(eng_sequences_padded, mni_sequences_padded, epochs=150, validation_split=0.2)


Epoch 1/100
252/252 [==============================] - 17s 13ms/step - loss: 1.1274 - accuracy: 0.7239 - val_loss: 0.9555 - val_accuracy: 0.7509
Epoch 2/100
252/252 [==============================] - 2s 9ms/step - loss: 0.9753 - accuracy: 0.7410 - val_loss: 0.8763 - val_accuracy: 0.7600
Epoch 3/100
252/252 [==============================] - 2s 9ms/step - loss: 0.8456 - accuracy: 0.7610 - val_loss: 0.7460 - val_accuracy: 0.7873
Epoch 4/100
252/252 [==============================] - 2s 9ms/step - loss: 0.7153 - accuracy: 0.7875 - val_loss: 0.6306 - val_accuracy: 0.8159
Epoch 5/100
252/252 [==============================] - 3s 13ms/step - loss: 0.5774 - accuracy: 0.8263 - val_loss: 0.5456 - val_accuracy: 0.8369
Epoch 6/100
252/252 [==============================] - 2s 9ms/step - loss: 0.4674 - accuracy: 0.8575 - val_loss: 0.4646 - val_accuracy: 0.8615
Epoch 7/100
252/252 [==============================] - 2s 9ms/step - loss: 0.3744 - accuracy: 0.8860 - val_loss: 0.4927 - val_accuracy: 0.8

In [ ]:
model.save("/content/drive/MyDrive/Colab Notebooks/machinelstmmodelreal.bin")

###Testing

In [ ]:
import tensorflow as tf
model = tf.keras.models.load_model("/content/drive/MyDrive/Colab Notebooks/machinelstmmodelreal.bin")
# Read the test CSV file using pandas
test_data_frame = pd.read_json('/content/drive/MyDrive/Colab Notebooks/mni_test.json', lines=True)

# Copy the dataframe
test_features = test_data_frame.copy()



# Pop 'native word' and 'english word' columns from the test dataframe
test_mni_words = test_features.pop('native word')
test_eng_words = test_features.pop('english word')


In [ ]:
# Apply character splitting to English test dataframe
test_eng_words = test_eng_words.apply(split_word_into_characters)

# Apply character splitting to Manipuri test dataframe
test_mni_words = test_mni_words.apply(split_word_into_characters)

# Tokenization of test data
test_eng_sequences = eng_tokenizer.texts_to_sequences(test_eng_words)
test_mni_sequences = mni_tokenizer.texts_to_sequences(test_mni_words)

In [ ]:
# Padding of test sequences
test_eng_sequences_padded = pad_sequences(test_eng_sequences, maxlen=max_seq_length, padding='post')
test_mni_sequences_padded = pad_sequences(test_mni_sequences, maxlen=max_seq_length, padding='post')


In [ ]:
# Model Evaluation
evaluation = model.evaluate( test_eng_sequences_padded,test_mni_sequences_padded)
print(evaluation[1]*100)

153/153 [==============================] - 2s 9ms/step - loss: 0.7507 - accuracy: 0.8889
88.88506889343262


In [ ]:
import nltk
from nltk.translate.bleu_score import corpus_bleu

# Generate predictions using the trained model
predictions = model.predict(test_eng_sequences_padded)

# Convert predictions to text
predicted_sentences = []
for prediction in predictions:
    sentence = ""
    for index in np.argmax(prediction, axis=1):
        if index != 0:
            word = mni_tokenizer.index_word[index]
            sentence += word
    predicted_sentences.append(sentence)

# Convert ground truth Manipuri sentences to a list of lists
reference_sentences = [list(sentence) for sentence in test_mni_words]


#Reshaping the reference sentence and predicted sentences
reference_sentences  = [[char for char in sublist if char != ' '] for sublist in reference_sentences]
predicted_sentences= [list(string) for string in predicted_sentences]

# Compute BLEU score
bleu_score = corpus_bleu([[sentence] for sentence in reference_sentences], predicted_sentences)

print("BLEU score:", bleu_score)


# Function to calculate Character Error Rate (CER)
def character_error_rate(true, pred):
    dist = nltk.edit_distance(true, pred)
    return dist / len(true)


# Calculate CER for each predicted sentence
cer_scores = []
for true, pred in zip(reference_sentences, predicted_sentences):
    cer = character_error_rate(true, list(pred))
    cer_scores.append(cer)

average_cer = sum(cer_scores) / len(cer_scores)
print("Average CER:", average_cer)


153/153 [==============================] - 2s 7ms/step
BLEU score: 0.4979800119575156
Average CER: 0.3081052438845445


In [ ]:
print(reference_sentences[0])
print(predicted_sentences[0])

['ꯌ', 'ꯥ', 'ꯜ', 'ꯂ', 'ꯒ']
['ꯌ', 'ꯥ', 'ꯜ', 'ꯂ', 'ꯒ']


In [ ]:
# Function to predict transliteration
def predict_transliteration(input_word):
    # Preprocess input word
    input_word = split_word_into_characters(input_word)
    input_sequence = eng_tokenizer.texts_to_sequences([input_word])
    input_sequence_padded = pad_sequences(input_sequence, maxlen=max_seq_length, padding='post')

    # Perform prediction
    predicted_sequence = model.predict(input_sequence_padded)

    # Convert predicted sequence to text
    predicted_word = ''
    for seq in predicted_sequence[0]:
        index = np.argmax(seq)
        if index in mni_tokenizer.index_word:
            predicted_char = mni_tokenizer.index_word[index]
            if predicted_char != ' ':
                predicted_word += predicted_char
        else:
            predicted_word += ''

    return predicted_word

# Get user input for the input word
input_word = input("Enter an English word: ")

# Predict transliteration
predicted_transliteration = predict_transliteration(input_word)

# Print the results
print('Input:', input_word)
print('Predicted Transliteration:', predicted_transliteration)


Enter an English word: eigi
1/1 [==============================] - 0s 29ms/step
Input: eigi
Predicted Transliteration: ꯏꯩꯒꯤ
